#!/bin/bash
wget -O /www/xderm/xderm-mini https://raw.githubusercontent.com/hanifwidi17/xderm-mini_GUI/main/xderm-mini -q
wget -O /www/xderm/index.php https://raw.githubusercontent.com/hanifwidi17/xderm-mini_GUI/main/index.php -q
